# Python 的 50+ 練習：資料科學學習手冊

> 資料科學模組 NumPy 入門

[數據交點](https://www.datainpoint.com) | 郭耀仁 <yaojenkuo@datainpoint.com>

## 練習題指引

- 練習題閒置超過 10 分鐘會自動斷線，只要重新點選練習題連結即可重新啟動。
- 第一個程式碼儲存格會將可能用得到的模組載入。
- 如果練習題需要載入檔案，檔案會存放在 `/home/jovyan/data` 資料夾中。
- 練習題已經給定函數、類別、預期輸入或參數名稱，我們只需要寫作程式區塊。
- 說明（Docstring）會描述測試如何進行，閱讀說明能夠暸解預期輸入以及預期輸出之間的關係，幫助我們更快解題。
- 請在 `### BEGIN SOLUTION` 與 `### END SOLUTION` 這兩個註解之間寫作函數或者類別的程式區塊。
- 將預期輸出放置在 `return` 保留字之後，若只是用 `print()` 函數將預期輸出印出無法通過測試。
- 語法錯誤（`SyntaxError`）或縮排錯誤（`IndentationError`）等將會導致測試失效，測試之前應該先在筆記本使用函數觀察是否與說明（Docstring）描述的功能相符。
- 執行測試的步驟：
    1. 點選上方選單的 File -> Save Notebook 儲存 exercises.ipynb。
    2. 點選上方選單的 File -> New -> Terminal 開啟終端機。
    3. 在終端機輸入 `python 10-numpy/test_runner.py` 後按下 Enter 執行測試。

In [ ]:
import numpy as np

## 072. 自行定義函數 `create_first_ten_odds_array` 回傳一個外型為 `(10,)` 儲存前十個奇數的陣列。

- 預期輸入：None
- 預期輸出：`numpy.ndarray`

```
[ 1  3  5  7  9 11 13 15 17 19]
```

In [ ]:
def create_first_ten_odds_array() -> np.array:
    """
    >>> first_ten_odds_array = create_first_ten_odds_array()
    >>> first_ten_odds_array
    [ 1  3  5  7  9 11 13 15 17 19]
    >>> type(first_ten_odds_array)
    'numpy.ndarray'
    >>> first_ten_odds_array.shape
    (10,)
    """
    ### BEGIN SOLUTION
    out_arr = np.arange(1, 20, 2)
    return out_arr
    ### END SOLUTION

## 073. 自行定義函數 `create_a_square_matrix` 回傳一個外型為 `(n, n)`、全以 `fill_int` 填滿的陣列。

- 預期輸入：`int`
- 預期輸出：`numpy.array`

In [ ]:
def create_a_square_matrix(n: int, fill_int: int) -> np.array:
    """
    >>> create_a_square_matrix(2, 5566)
    [[5566 5566]
     [5566 5566]]
    >>> create_a_square_matrix(3, 55)
    [[55 55 55]
     [55 55 55]
     [55 55 55]]
    >>> create_a_square_matrix(4, 66)
    [[66 66 66 66]
     [66 66 66 66]
     [66 66 66 66]
     [66 66 66 66]]
    """
    ### BEGIN SOLUTION
    arr_shape = (n, n)
    out_arr = np.full(shape=arr_shape, fill_value=fill_int)
    return out_arr
    ### END SOLUTION

## 074. 自行定義函數 `create_a_diagonal_matrix` 回傳一個外型 `(n, n)`、對角線數字為 `fill_int` 的陣列。

參考 NumPy 函數 `eye`：<https://numpy.org/doc/stable/reference/generated/numpy.eye.html>

- 預期輸入：`int`
- 預期輸出：`numpy.array`

In [ ]:
def create_a_diagonal_matrix(n: int, fill_int: int) -> np.array:
    """
    >>> create_a_diagonal_matrix(2, 5566)
    [[5566    0]
     [   0 5566]]
    >>> create_a_diagonal_matrix(3, 55)
    [[55  0  0]
     [ 0 55  0]
     [ 0  0 55]]
    >>> create_a_diagonal_matrix(4, 66)
    [[66  0  0  0]
     [ 0 66  0  0]
     [ 0  0 66  0]
     [ 0  0  0 66]]
    """
    ### BEGIN SOLUTION
    identity_matrix = np.eye(n, dtype=int)
    out_arr = identity_matrix * fill_int
    return out_arr
    ### END SOLUTION

## 075. 自行定義函數 `create_nine_nine_array` 回傳一個外型為 `(9, 9)` 九九乘法陣列。

- 預期輸入：None
- 預期輸出：`numpy.array`

```
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
```

In [ ]:
def create_nine_nine_array() -> np.array:
    """
    >>> nine_nine_array = create_nine_nine_array()
    >>> nine_nine_array.shape
    (9, 9)
    >>> nine_nine_array[0, 0]
    1
    >>> nine_nine_array[1, 1]
    4
    >>> nine_nine_array[7, 7]
    64
    >>> nine_nine_array[8, 8]
    81
    """
    ### BEGIN SOLUTION
    nine_one_array = np.arange(1, 10).reshape(9, 1)
    one_nine_array = np.arange(1, 10).reshape(1, 9)
    nine_nine_array = nine_one_array.dot(one_nine_array)
    return nine_nine_array
    ### END SOLUTION

## 076. 自行定義函數 `filter_evens` 回傳輸入陣列中的偶數部分。

- 預期輸入：`numpy.array`
- 預期輸出：`numpy.array`

In [ ]:
def filter_evens(x: np.array) -> np.array:
    """
    >>> filter_evens(np.array([5, 5, 6, 6]))
    array([6, 6])
    >>> filter_evens(np.array([1, 2, 3, 4]))
    array([2, 4])
    >>> filter_evens(np.array([0, 1, 2, 3]))
    array([0, 2])
    """
    ### BEGIN SOLUTION
    evens = x[x % 2 == 0]
    return evens
    ### END SOLUTION